In [1]:
import numpy as np
import random

In [2]:
# file_data = open(r"C:\Users\rohan\Downloads\arr20.txt", "r")
# print(file_data.read())

In [3]:
def generate_inputfiles():
    data_count = [20,100,1000,4000]
    for count in data_count:
        newline_flag = 0
        file = open("input_files/arr"+str(count)+".txt","w")
        for iter in range(0,count):
            if newline_flag == 1:
                file.write("\n")
            num1 = random.randrange(0,99,1)
            num2 = random.randrange(0,99,1)
            num3 = random.randrange(0,99,1)
            file.write(str(num1)+" "+str(num2)+" "+str(num3))
            newline_flag = 1
        file.close()

In [4]:
# # X = np.array([])
# for x in file_data.read():
#     print(x)
    

In [5]:
def readfile_data(count):
    file = open("input_files/arr"+str(count)+".txt","r")
    datalist = []
    for line in file:
        num1, num2, num3 = line.split()
        num1, num2, num3 = int(num1), int(num2), int(num3)
        #datalist.append({"num1":num1,"num2":num2,"num3":num3,"sum":num1+num2+num3})
        datalist.append([num1,num2,num3,num1+num2+num3])
    return datalist

In [6]:
# print(X)

In [7]:
def save_data(count, datalist):
    file = open("output_files/arrIS_O_"+str(count)+".txt","w")
    newline_flag = 0
    for data in datalist:
        if newline_flag == 1:
            file.write("\n")
        num1, num2, num3, sum = str(data[0]),str(data[1]),str(data[2]),str(data[3])
        file.write(num1+" "+num2+" "+num3+" "+sum)
        newline_flag = 1
    file.close()

In [8]:
def insertionsort(datalist):
    M = len(datalist)
    N = 4
    X1 = np.array(datalist)
    for i in range(1,M):
        temp1 = np.array(X1[i])
    #     print(temp1[N-1])
    #     print(temp1)
        k = i-1
        while (k>=0) and (X1[k,N-1] > temp1[N-1]):
            X1[[k+1]] = X1[[k]]
            k = k-1
        X1[[k+1]] = temp1
    datalist = np.array(X1)
    return datalist

In [9]:
generate_inputfiles()

datalist = readfile_data(20)

datalist.sort(key=lambda row:(row[3]))
datalist = insertionsort(datalist)
print(datalist)

save_data(20, datalist)

[[ 30   2  39  71]
 [ 17   8  46  71]
 [ 60   5  31  96]
 [  7  71  26 104]
 [ 50  56   0 106]
 [  6  67  44 117]
 [ 19  73  26 118]
 [ 81   9  31 121]
 [ 55  67  13 135]
 [ 72  21  48 141]
 [ 29  51  65 145]
 [ 28  41  80 149]
 [ 47  32  72 151]
 [ 19  62  75 156]
 [ 75  42  40 157]
 [ 75  17  68 160]
 [ 92  37  50 179]
 [ 64  75  41 180]
 [ 96  80   5 181]
 [ 85  39  62 186]]
